<div class="jumbotron">
    <h1><?= $this->translate('Welcome to') ?> <span class="zf-green"><?= $this->translate('Zend Framework') ?></span>
    </h1>

    <p>
        <?= $this->translate('Congratulations!') ?> <?= $this->translate('You have successfully installed the') ?>
        <a href="https://github.com/zendframework/ZendSkeletonApplication"
           target="_blank"><?= $this->translate('ZF Skeleton Application') ?></a>.
        <?= $this->translate('You are currently running Zend Framework version') ?> <?= \Application\Module::VERSION ?>.
        <?= $this->translate('This skeleton can serve as a simple starting point for you to begin building your application on ZF.') ?>
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework"
          target="_blank"><?= $this->translate('Fork') ?>
            <?= $this->translate('Zend Framework') ?> <?= $this->translate('on') ?> GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"><?= $this->translate('Follow Development') ?></h2>
            </div>
            <div class="card-body">
                <p>
                    <?= $this->translate('Zend Framework is under active development. If you are interested in following the development of ZF, you can check') ?>
                    <a href="http://framework.zend.com/blog/"><?= $this->translate('ZF dev blog') ?></a>,
                    <?= $this->translate('and') ?> <a
                            href="https://github.com/issues?utf8=%E2%9C%93&amp;q=is:issue+org:zendframework">
                        <?= $this->translate('ZF issue tracker') ?></a>
                    <?= $this->translate('(link requires a GitHub account). This is a great resource for staying up to date with the latest developments!') ?>
                </p>

                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/" target="_blank">
                        <?= $this->translate('ZF Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"><?= $this->translate('Discover Modules') ?></h2>
            </div>
            <div class="card-body">
                <p>
                    <?= $this->translate('The community is working on developing a community site to
                    serve as a repository and gallery for ZF modules. The project is available') ?>
                    <a href="https://github.com/zendframework/modules.zendframework.com">
                        <?= $this->translate('on') ?> GitHub</a>.
                    <?= $this->translate('The site is currently live and currently contains a list of
                    some of the modules already available for ZF.') ?>
                </p>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">
                        <?= $this->translate('Explore ZF Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"><?= $this->translate('Help &amp; Support') ?></h2>
            </div>
            <div class="card-body">
                <p>
                    <?= $this->translate('If you need any help or support while developing with ZF, you may reach us via IRC:')?>
                    <a href="irc://irc.freenode.net/zftalk">#zftalk <?= $this->translate('on')?> Freenode</a>.
                    <?= $this->translate('We\'d love to hear any questions or feedback you may have regarding this release.')?>
                    <?= $this->translate('Alternatively, you may subscribe and post questions to the')?>
                    <a href="http://framework.zend.com/archives/"><?= $this->translate('mailing lists')?></a>.
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk"
                      target="_blank"><?= $this->translate('Ping us on IRC')?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
